<?php

namespace GRH\GrhBundle\Repository;

/**
 * CondidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondidatRepository extends \Doctrine\ORM\EntityRepository
{
	public function sescondidats($id){
		$query = $this->_em->createQuery("SELECT c FROM GRHGrhBundle:Condidat c where c.id =$id");
          $resultats = $query->getResult();
          return $resultats;		
	}
}
