<?php

namespace GRH\GrhBundle\Repository;

/**
 * RecrutementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementRepository extends \Doctrine\ORM\EntityRepository
{
	public function recrutouvert(){
		$query = $this->_em->createQuery("SELECT r FROM GRHGrhBundle:Recrutement r where r.status ='ouvert'");
          $resultats = $query->getResult();
          return $resultats;		
	}
}
