<?php

namespace COMPTABILITE\CompBundle\Repository;

/**
 * DepenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenceRepository extends \Doctrine\ORM\EntityRepository
{
}
