<?php

namespace COMPTABILITE\CompBundle\Repository;

/**
 * LignefactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefactureRepository extends \Doctrine\ORM\EntityRepository
{
}
