<?php

namespace CRM\CrmBundle\Repository;

/**
 * CompagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagneRepository extends \Doctrine\ORM\EntityRepository
{
}
