<?php

namespace CRM\CrmBundle\Repository;

/**
 * OpportuniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportuniteRepository extends \Doctrine\ORM\EntityRepository
{
	public function fermeroppor(){
		$query = $this->_em->createQuery("SELECT o FROM CRMCrmBundle:Opportunite o where o.fermer ='non'");
          $resultats = $query->getResult();
          return $resultats;
	}

	public function opportunitesouvert(){
		$query = $this->_em->createQuery("SELECT o FROM CRMCrmBundle:Opportunite o where o.fermer ='non'");
          $resultats = $query->getResult();
          return $resultats;
	}

	public function opportunitesferme(){
		$query = $this->_em->createQuery("SELECT o FROM CRMCrmBundle:Opportunite o where o.fermer ='oui'");
          $resultats = $query->getResult();
          return $resultats;
	}

	public function opportunitesperdus(){
		$query = $this->_em->createQuery("SELECT o FROM CRMCrmBundle:Opportunite o where o.gagnier ='non'");
          $resultats = $query->getResult();
          return $resultats;
	}

	public function opportunitesganiger(){
		$query = $this->_em->createQuery("SELECT o FROM CRMCrmBundle:Opportunite o where o.gagnier ='oui'");
          $resultats = $query->getResult();
          return $resultats;
	}
}
