<?php

namespace CRM\CrmBundle\Repository;

/**
 * RendezvousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezvousRepository extends \Doctrine\ORM\EntityRepository
{
	public function rdvarriver(){
		$query = $this->_em->createQuery("SELECT r FROM CRMCrmBundle:Rendezvous r where r.debut >=CURRENT_DATE() ORDER BY r.debut asc");
          $resultats = $query->getResult();
          return $resultats;
	}
}
