<?php

namespace CRM\ClientBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function danger_service($id){
		$query = $this->_em->createQuery("SELECT COUNT(s) FROM CRMClientBundle:Service s where s.client = $id And s.etat='non_consulter'  
			 ");
          $resultats = $query->getSingleScalarResult();
          return $resultats;
	}

	public function serviceenattent(){
		$query = $this->_em->createQuery("SELECT s FROM CRMClientBundle:Service s where s.etat = 'en_attente' OR s.etat='non_consulter'  
			 ");
          $resultats = $query->getResult();
          return $resultats;
	}

	public function services(){
		$query = $this->_em->createQuery("SELECT s FROM CRMClientBundle:Service s where s.etat = 'en_attente' OR s.etat='consulter'  
			 ");
          $resultats = $query->getResult();
          return $resultats;
	}
}
