<?php

namespace STOCK\StockBundle\Repository;

/**
 * BonreceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonreceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
