<?php

namespace STOCK\StockBundle\Repository;

/**
 * LignebonreceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignebonreceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
